### ISSUE TITLE
Mailbox settings: set sent = +Sent

### ISSUE THREAD

**Issue by jtorrex** [flaport/blog#1]
Hi Floris!

First, congrats for your posts, I'm configuring too neomutt + mbsync + msmtp as my daily mail MUA and your post was very useful for me.

I think that there is an error on the **_"Setting up neomutt"_** section, just when you define the **_#mailbox settings_**.

The line:

`set sent = +Sent`

Should be

`set record = +Sent`

If not, neomutt throw this error:

**line 35: sent: unknown variable**

Find for 'record' var in the neomutt manual to verify it:

[(https://neomutt.org/man/neomuttrc#algolia:div%20%3E%20div:nth-of-type(6)%20%3E%20div%20%3E%20dl%20%3E%20dd:nth-of-type(187)%20%3E%20p)](url)

Here is another example on section Example 3.7:

[https://neomutt.org/guide/configuration#algolia:div%20%3E%20div:nth-of-type(27)%20%3E%20div:nth-of-type(4)%20%3E%20div:nth-of-type(3)%20%3E%20p:nth-of-type(4)](url)

Regards and thanks for your blog!

**Comment by flaport** [comment]
Good find! Thanks 🙂

I updated the post.
